import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-poppins"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} bg-white! text-black!`}
      >
        <NavBar/>
        <main className="max-w-350 mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
